M48
; DRILL file {KiCad 7.0.5} date Fri Jul  7 19:33:19 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-07T19:33:19+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1260
%
G90
G05
T1
X6.8799Y-2.0045
X6.8799Y-2.2014
T2
X4.9122Y-3.8258
T3
X5.2075Y-3.8258
T4
X7.0563Y-4.0476
T5
X4.4776Y-1.6754
X4.4862Y-4.0515
X7.0563Y-1.6754
T0
M30
